### ISSUE TITLE
Still unable to get propertree working on Monterey (12.3.1) with python 3.10.4 and tkinter 3.10.4

### ISSUE THREAD

**Issue by kfkahhdickans** [corpnewt/ProperTree#129]
Using buildapp-select.command I use python3 which is set to python 3.10 using macports (python3 --version results in Python 3.10.4) and it successfully builds the app. The resulting app however still just is a black window. If I instead try to use ProperTree.command I get the following error in terminal:  

`> ./ProperTree.command
Traceback (most recent call last):
  File "/Users/#/Downloads/ProperTree-master/./ProperTree.py", line 1338, in <module>  
    p = ProperTree(plists)  
  File "/Users/#/Downloads/ProperTree-master/./ProperTree.py", line 29, in __init__
      self.tk = tk.Tk()  
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 2299, in __init__    
      self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)    
_tkinter.TclError: no display name and no $DISPLAY environment variable`

I'm quite familiar with python, not with tkinter however, so no idea what to do here.
Googling that last line doesn't get you anything useful either.
Some people suggest installing XQuartz as MacOS doesn't have a $DISPLAY environment variable and only X does.
That obviously didn't work.
I have also tried using python and tkinter 3.9 and 3.10 from python.org and from homebrew, but the results were all the same.
Running buildapp-select.py or ProperTree.py instead also makes no difference.
Also any reason why there isn't a prebuilt .app made available?

**Comment by corpnewt** [comment]
> Running buildapp-select.py or ProperTree.py instead also makes no difference.

Can you show me what output you get with `buildapp-select.command`, and what you're selecting in that menu?  After building the .app, you should also be launching the newly created `ProperTree.app` that's in the same directory as your `ProperTree.command` file - as this has its shebang hard-coded by `buildapp-select.command`.

> Also any reason why there isn't a prebuilt .app made available?

I tend to update things in spurts - and honestly only do this as a hobby.  If you'd like to submit a PR to auto-build or similar, you're welcome to, but that's out of my wheelhouse currently.  In my use-cases, I've not had issues on any of my current 4 Hackintoshes with `buildapp-select.command` not building a working `ProperTree.app` when selecting the python installation from python.org.

-CorpNewt

**Comment by j-autuick** [comment]
I am having the same problem trying to launch properTree from Monterey
![Screenshot 2022-06-13 at 08 18 40](https://user-images.githubusercontent.com/11945056/173291603-f06361c6-908e-4c88-8193-01277656f2b5.png)
.
