### ISSUE TITLE
ModuleNotFoundError: No module named 'Tkinter'

### ISSUE THREAD

**Issue by rehack** [corpnewt/ProperTree#158]
OS version: windows 10
python version: 3.11.2
ProperTree: last version

Running ProperTree.command and ProperTree.bat will cause errors：
![1](https://user-images.githubusercontent.com/9047357/220927300-11e7ac20-f41d-4766-bd3f-1e427ae1c576.PNG)
![2](https://user-images.githubusercontent.com/9047357/220927318-92d11865-14ab-420a-8172-88c8725cebdb.PNG)

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rehack** [comment]
I tested propertree  a black UI on the macos.
![image](https://user-images.githubusercontent.com/9047357/222913902-681e413a-3d22-4e85-b8ec-96f3b0d810bb.png)

**Comment by pavlinbl4** [comment]
Same problem LinuxMint
'3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]
Python 3.8.10

`Traceback (most recent call last):
  File "./ProperTree/ProperTree.py", line 5, in <module>
    import Tkinter as tk
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ProperTree/ProperTree.py", line 12, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
`

**Comment by pavlinbl4** [comment]
It's way to solve this https://stackoverflow.com/questions/34399387/linux-mint-17-tkinter-not-installed

**Comment by KlavierGayming** [comment]
pip3 install tkinter 
should do the trick

you can use brew on macOS

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by panosru** [comment]
just run `brew install python-tk`

**Comment by Sauvio** [comment]
I've solved this problem this way on macOS catalina 10.15.6.
I got "Tk older than 8.5.12 not supported." in the log, because the system provided Tcl/Tk libraries are too old.
refer to this:
 #[](https://github.com/Homebrew/homebrew-core/issues/73987)

The following is how I fixed it.
1.  install dependence
refer to this:
[](https://stackoverflow.com/questions/22550068/python-not-configured-for-tk/55441855#55441855)

2. Let's say you're using pyenv.
```
pyenv version
pyenv global <version>
```
4. Link to your python3 version
`brew unlink python3 && sudo ln -snf /Users/sauvio/.pyenv/versions/3.11.2/bin/python3 /usr/bin/python3`

finally I can run `ProperTree.command` without errors.

**Comment by Yihang2011** [comment]
``pip install tkinter`` for windows

``brew install python-tk`` for macOS

``sudo apt install python-tk`` for linux(ubuntu)

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mikebeaton** [comment]
> `sudo apt install python-tk` for linux(ubuntu)

`sudo apt install python3-tk` worked for me

**Comment by dakshshrivastav** [comment]
#69 i solved it by installing tk from pamac (pacman gui on manjaro back from 2020)
