### ISSUE TITLE
Sonoma: No content rendered with no matter whilch file is open

### ISSUE THREAD

**Issue by Wohlstand** [corpnewt/ProperTree#172]
Recently I tried to run the ProperTree thing on macOS Sonoma, and it's totally unable to render anything: I do see the blank window, even I opened any file and when I am able to scroll through it, but it can't render the content at all... As an example, I opened the existing `snapshot.plist` file from the `Scripts` directory of ProperTree itself.

![Снимок экрана 2024-03-14 в 07 45 03](https://github.com/corpnewt/ProperTree/assets/6751442/dbbd15c5-9899-4c7e-96db-3b7126c47684)

Note: The rest of errors shown after I closed the Unitled.plist window.

Output:
```
/Users/vitaly/Repos/ProperTree/ProperTree.command ; exit;                       
vitaly@Mac-mini-Vitalij ~ % /Users/vitaly/Repos/ProperTree/ProperTree.command ; exit;
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2024-03-14 07:44:20.577 Python[25749:129537] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 3172, in popup
    if cell: self.select(cell,alternate=False)
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 3431, in select
    if see: self._tree.see(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/ttk.py", line 1417, in see
    self.tk.call(self._w, "see", item)
_tkinter.TclError: invalid command name ".!plistwindow2.!frame.!treeview"
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1636, in open_plist
    return self.pre_open_with_path(path)
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1652, in pre_open_with_path
    return self.open_plist_with_path(None,path,current_window)
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1677, in open_plist_with_path
    current_window.open_plist(path,plist_data,plist_type,self.settings.get("expand_all_items_on_open",True))
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 2412, in open_plist
    self.select(root)
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 3431, in select
    if see: self._tree.see(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/ttk.py", line 1417, in see
    self.tk.call(self._w, "see", item)
_tkinter.TclError: invalid command name ".!plistwindow2.!frame.!treeview"
Traceback (most recent call last):
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1276, in check_open
    self.start_window = self.new_plist()
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1622, in new_plist
    window.open_plist(final_title.capitalize(),{}) # Created an empty root
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 2412, in open_plist
    self.select(root)
  File "/Users/vitaly/Repos/ProperTree/Scripts/plistwindow.py", line 3431, in select
    if see: self._tree.see(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/ttk.py", line 1417, in see
    self.tk.call(self._w, "see", item)
_tkinter.TclError: invalid command name ".!plistwindow.!frame.!treeview"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1773, in <module>
    p = ProperTree(plists)
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 515, in __init__
    self.check_open(plists)
  File "/Users/vitaly/Repos/ProperTree/ProperTree.py", line 1278, in check_open
    self.tk.bell()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 851, in bell
    self.tk.call(('bell',) + self._displayof(displayof))
_tkinter.TclError: can't invoke "bell" command:  application has been destroyed

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Wohlstand** [comment]
Okay, I found solution by myself: I forgot to install `brew install python-tk` thing. Now it works as expected:

![Снимок экрана 2024-03-14 в 07 51 19](https://github.com/corpnewt/ProperTree/assets/6751442/0f37689d-b3d2-49a2-a00b-b8e70e821554)
