### ISSUE TITLE
Linux: Can't save file or CTRL+C a tree

### ISSUE THREAD

**Issue by realmayus** [corpnewt/ProperTree#31]
I get this error in the console when trying to save a .plist file or trying to copy a tree:
```
Traceback (most recent call last):
  File "/home/marius/ProperTree/Scripts/plistwindow.py", line 1606, in copy_children
    clipboard_string = plist.dumps(plist_data,sort_keys=self.controller.settings.get("sort_dict",False))
TypeError: expected bytes, str found
TypeError: expected bytes, str found
Exception ignored in: 'plist.create_dict_plist'
Traceback (most recent call last):
  File "/home/marius/ProperTree/Scripts/plistwindow.py", line 1606, in copy_children
    clipboard_string = plist.dumps(plist_data,sort_keys=self.controller.settings.get("sort_dict",False))
TypeError: expected bytes, str found```

**Comment by corpnewt** [comment]
Has to do with python3 on arch linux.  References [here](https://github.com/corpnewt/ProperTree/issues/19), [here](https://github.com/corpnewt/ProperTree/issues/22) and [here](https://github.com/corpnewt/ProperTree/issues/28).  You can either use python 2, or remove `libplist`.

-CorpNewt

**Comment by realmayus** [comment]
Yup, that worked, thanks :)
