### ISSUE TITLE
Cannot run the app from macOS

### ISSUE THREAD

**Issue by walteweiss** [corpnewt/ProperTree#34]
Before installing py38-tkinter (and  `Xft2`, `tcl`, `tk`, `xorg-libXScrnSaver` as dependencies) plus later `pypy3-tkinter` (and `pypy3` as dependency) I had an issue telling me something about tk. I haven't saved it unfortunately. I installed the packages, and now it shows me this error message:

```
Traceback (most recent call last):
  File "./ProperTree.command", line 557, in <module>
    p = ProperTree(plists)
  File "./ProperTree.command", line 21, in __init__
    self.tk = tk.Tk()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

macOS Catalina 10.15.5 (19F96)
I use [MacPorts](https://www.macports.org/), if that changes anything. I used ProperTree a couple of months ago and it worked well. Though at that time I used Mojave and [brew](https://brew.sh/) as my package manager.

**Comment by olorton** [comment]
I got this working by following these instructions: https://stackoverflow.com/a/55441855/2554826

This should probably be added to the README
