### ISSUE TITLE
Unable to Run ProperTree on Linux Mint

### ISSUE THREAD

**Issue by jdferron** [corpnewt/ProperTree#42]
Installed Ubuntu's Python3-tk package (3.6.9-1~18.04) on LinuxMint XFCE, then ran ProperTree.command and am receiving the following error:

jeff@rye:~/Downloads$ ./ProperTree.command 
Traceback (most recent call last):
  File "./ProperTree.command", line 10, in <module>
    import tkinter as tk

**Comment by kittywhiskers** [comment]
Try to run it as `python3 ProperTree.command`

**Comment by jdferron** [comment]
Thanks! That worked.   The readme should be updated.

**Comment by araujogui** [comment]
on Fedora, `sudo dnf install python3-tkinter` solves the issue.

**Comment by cheesycod** [comment]
@jdferron You installed Python3-tk, not Python2-tk, linux mint aliases python to py2 IIRC

**Comment by User13244567** [comment]
@kittywhiskers this command didn't work for me it gives me this error 

  File "/home/andre/Downloads/ProperTree-master/ProperTree.command", line 18
    compare_to_version () {
                          ^
SyntaxError: invalid syntax

**Comment by TrippsQ** [comment]
> 

SAME EXACT ISSUE :(

**Comment by corpnewt** [comment]
How are you launching ProperTree?

-CorpNewt

**Comment by TrippsQ** [comment]
I am trying to install mac os using linux mint.

First I created a terminal within the proper tree folder

then I "Sudo python3 ProperTree.command"

I get an error about a "{" on line 18. Ive tried fixing it manually but the
error just moves down to the next thing

**Comment by TrippsQ** [comment]
maybe i dont put sudo, sorry im not in front of the machine right now. But i think ive tried with and without sudo

**Comment by TrippsQ** [comment]
> How are you launching ProperTree?
> 
> -CorpNewt

^

**Comment by corpnewt** [comment]
ProperTree.command is not a python file - it's a bash file.  If you want to pipe a file directly to python, you need to use `python3 ProperTree.py` (or `python ProperTree.py` on Windows, or systems with only python 2).

-CorpNewt

**Comment by TrippsQ** [comment]
Thanks man, so new to linux

**Comment by corpnewt** [comment]
You're welcome - it has little to do with Linux though.  Just knowing what files to do what with.  Glad that helped though.

-CorpNewt

**Comment by TrippsQ** [comment]
> You're welcome - it has little to do with Linux though. Just knowing what files to do what with. Glad that helped though.
> 
> -CorpNewt

Do you have any tips for what to do if you try to get a module (python-tk) but the site is down?

**Comment by corpnewt** [comment]
I'm sorry, but that's not really in my wheelhouse, nor a topic for this issue thread.  I wish you luck though.

-CorpNewt

**Comment by theFranco2** [comment]
I also had that issue on my computer with Arch Linux, and I resolved it by installing Tkinter with this command: `sudo pacman -S tk`. Afterward, I ran the program using `python3 ProperTree.py.`
