### ISSUE TITLE
global name 'plist' is not defined

### ISSUE THREAD

**Issue by MammaScan** [corpnewt/ProperTree#56]
Running the .command or the script made propertree.app only gives me this kind of errors.
`andersbergman@Anderss-iMac ~ % /Volumes/\[Storage\]/OSX\ FIX/ProperTree-master/ProperTree.command ; exit;
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 596, in callit
    func(*args)
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 206, in <lambda>
    self.tk.after(250, lambda:self.check_open(plists))
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 244, in check_open
    self.start_window = self.new_plist()
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 484, in new_plist
    window = plistwindow.PlistWindow(self, self.tk)
NameError: global name 'plistwindow' is not defined
`

**Comment by MammaScan** [comment]
Still can't figure this out. It works on Win10 but not on Catalina with "osx-stock python 2.7.16".
Then I installed python3.9 but it gave me ALMOST the same result
`Last login: Wed Nov 25 01:35:22 on ttys000
/Volumes/\[Storage\]/OSX\ FIX/ProperTree-master/ProperTree.command ; exit;
andersbergman@Anderss-iMac ~ % /Volumes/\[Storage\]/OSX\ FIX/ProperTree-master/ProperTree.command ; exit;
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 806, in callit
    func(*args)
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 206, in <lambda>
    self.tk.after(250, lambda:self.check_open(plists))
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 244, in check_open
    self.start_window = self.new_plist()
  File "/Volumes/[Storage]/OSX FIX/ProperTree-master/ProperTree.command", line 484, in new_plist
    window = plistwindow.PlistWindow(self, self.tk)
NameError: name 'plistwindow' is not defined
`
Could it have anything to do with tkinter not working as it should on my machine?

**Comment by afinotti** [comment]
I have the same issue. With stock BigSur Python ProperTree didnt open. With Python 3.9.1 It open but can't open config.plist 
Message i get: name 'plist' is not defined.

**Comment by soundflix** [comment]
I had error "name 'plistwindow' is not defined" after I moved the ProperTree-Folder. I downloaded Python directly from Python.org, installed that and then I re-downloaded ProperTree package and rebuilt the .app with the new Python bundle and it works again.
