### ISSUE TITLE
"New top level entry" creating glitch entry

### ISSUE THREAD

**Issue by M4kI9H7** [corpnewt/ProperTree#89]
Reproduce:
1. Have a Root Dictionary with at least one item inside
2. Collapse Root entry
3. On context menu, "New top level entry"
4. A glitch item is created, with its name (blank), type String, and empty value.

On terminal log:
> Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/Users/m4ki9h7/Documents/Hackintosh Tools&Backup/ProperTree/Scripts/plistwindow.py", line 2646, in on_double_click
    if parent == "" and (index == 0 or self.get_check_type(self.get_root_node()).lower() in ("array","dictionary")): return 'break' # Not changing the type - can't change the name of Root
  File "/Users/m4ki9h7/Documents/Hackintosh Tools&Backup/ProperTree/Scripts/plistwindow.py", line 2711, in get_root_node
    if not len(children) == 1: raise Exception("Root is malformed!")

Notes:
* Unable to save the file in this state
* Moving, Dragging, Deleting, Adding(context menu doesn't appear) functions nonresponsive, otherwise working as intended

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/ProperTree/commit/6e9e9420807859d34602d8ccdbce031a88917890).

-CorpNewt
